In [2]:
"""NumPy Tutorial: Learn NumPy in 30 Minutes

This notebook provides a comprehensive introduction to NumPy, the fundamental package for scientific computing in Python.

What is NumPy?

. NumPy (Numerical Python) is a library for the Python programming language
. It provides support for large, multi-dimensional arrays and
. Includes a collection of mathematical functions to operate
. Essential for data science, machine learning, and scientific computing

Learning Objectives:

1. Understand NumPy arrays and their advantages
2. Create and manipulate arrays
3. Perform mathematical and statistical operations
4. Use indexing and slicing effectively
5. Apply NumPy to real-world problems

"""

import numpy as np

In [3]:
python_list=[1,2,3,4]
print(type(python_list))

<class 'list'>


In [4]:
numpy_array=np.array((1,2,3,4,5))
print(numpy_array)

[1 2 3 4 5]


In [5]:
import time

In [6]:
print(time.localtime())

time.struct_time(tm_year=2026, tm_mon=5, tm_mday=19, tm_hour=16, tm_min=24, tm_sec=19, tm_wday=1, tm_yday=139, tm_isdst=0)


In [7]:
#large array
size=100000
python_list=list(range(0,100001))
print(type(python_list))
numpy_array=np.arange(size)
print(numpy_array)

<class 'list'>
[    0     1     2 ... 99997 99998 99999]


In [8]:
#Additional operation
print(f"array size: {size:,} elements\n")

array size: 100,000 elements



In [9]:
start = time.time()

for i in range(1000000):
    pass

end = time.time()

print("Time:", end - start)

Time: 0.05427813529968262


In [10]:
for i in range(5):
    
    

_IncompleteInputError: incomplete input (76358646.py, line 3)

In [11]:
#python list
arr1=np.array([1,2,3,4])
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4]


In [12]:
#similiar to range()
arr2=np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [13]:
#start, stop, number of elements
arr3=np.linspace(0,1,5)
print(arr3)

# Method 4: Creating arrays of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Method 5: Creating arrays of ones
ones = np.ones(5)
print("Ones:", ones)

# Method 6: Creating arrays with a specific value
full = np.full(5, 7) # shape, fill_value
print("Full (all 7s):", full)

# Method 7: Identity matri
identity = np.eye(3)
print("Identity matrix:n", identity)

# Method 8: Random arrays
random_arr = np.random.rand(5) # Uniform distribution [0, 1)
print("Random (uniform):", random_arr)

random_int = np.random.randint(1, 10, size=5) # [low, high), size
print("Random integers:", random_int)

[0.   0.25 0.5  0.75 1.  ]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full (all 7s): [7 7 7 7 7]
Identity matrix:n [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random (uniform): [0.64132511 0.30257721 0.79626383 0.63468255 0.24716224]
Random integers: [9 2 9 5 7]


In [14]:
"""NumPy Data Types

NumPy arrays are homogeneous - all elements have the same type. Types affect memory usage and operations.
"""

# Type inference and common types
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3]) # Mixed types - promo

print(f"Integer: {arr_int.dtype}")
print(f"Float: {arr_float.dtype}")
print(f"Mixed: {arr_mixed.dtype} (promoted to float)\n")

# Specifying types
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = arr_int.astype(np.float64) # Convert types

print(f"Specified float32: {arr1.dtype}")
print(f"Converted to float64: {arr2.dtype}\n")

# Common types: int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")

Integer: int64
Float: float64
Mixed: float64 (promoted to float)

Specified float32: float32
Converted to float64: float64

Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


In [15]:
#Multi-dimensional Arrays

# 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}") # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}") # Number of dimensions
print(f"Size: {matrix_2d.size}") # Total number of elem
print(f"Data type: {matrix_2d.dtype}") # Data type of e

# 3D array
matrix_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(matrix_3d)
print(f"Shape: {matrix_3d.shape}") # (depth, rows, columns)

# Creating multi-dimensional arrays with specific shapes
zeros_2d = np.zeros((3, 4)) #3 rows, 4 columns
print("\n2D zeros array:")
print(zeros_2d)

ones_3d= np.ones((2,3,4)) #2x3x4 array
print(f"\n3D ones array shape: {ones_3d.shape}")

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)

2D zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3D ones array shape: (2, 3, 4)


In [16]:
#Array Attributes and Information
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}") # Dimensions of the array
print(f"Size: {arr.size}") # Total number of elements
print(f"ndim: {arr.ndim}") # Number of dimensions
print(f"dtype: {arr.dtype}") # Data type
print(f"itemsize: {arr.itemsize} bytes") # Size of each element
print(f"nbytes: {arr.nbytes} bwtes") # Total memory used
# Transpose of the array

print(f"T (transpose) : n{arr.T}")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
ndim: 2
dtype: int64
itemsize: 8 bytes
nbytes: 96 bwtes
T (transpose) : n[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [17]:
arr = np.array([10,20, 30,40, 50])

# 1D indexing (same as Python lists)
print("Original array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements 1 to 3:", arr[1:4]) # Slicing: [start:stop:step]
print("Every other element:", arr[ : :2])

# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])
print("\n2D Array:")
print(matrix)
print("Element at row 1, column 2:", matrix[1, 2]) # Row, Column
print("First row:", matrix[0, :]) # All columns of first row
print("Second column:", matrix[:, 1]) # All rows of second column
print("Submatrix (first 2 rows, first 2 columns):")
print(matrix[0:2,0:2])

# Boolean indexing - powerful feature!
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n --- Boolean Indexing --- ")
print("Original:", arr)
print("Elements greater than 5:", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])

Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every other element: [10 30 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix (first 2 rows, first 2 columns):
[[1 2]
 [4 5]]

 --- Boolean Indexing --- 
Original: [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]


In [18]:
#Arrays manipulation
arr = np.arange(20)
print("Original 1D array:", arr)

# Reshape - changes view, doesn't copy data
reshaped = arr.reshape(4, 5) # Must match total size (3*4=12)
print("\nReshaped to 3x4:")
print(reshaped)

# Flatten - convert to 1D
flattened = reshaped.flatten()
print("\nFlattened:", flattened)

# Reshape with -1 (auto-calculate dimension)
auto_reshape = arr.reshape(2, -1) # -1 means "calculate automatically" no. of column and -1 represent 
                                  #the set the no. in the own way
print("\nAuto reshape (2 rows, auto columns):")
print(auto_reshape)

# Transpose
matrix = np.array([[1, 2, 3], [4,5,6]])
print("\nOriginal matrix:")
print(matrix)
print("Transposed:")
print(matrix.T)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped to 3x4:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Auto reshape (2 rows, auto columns):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]


In [19]:
"""Understanding Dimensions and Axis

Key Concepts:

· Dimension (ndim): Number of axes (1D=1, 2D=2, 3D=3)
. Axis: The dimension along which an operation is performearts at 0)
· Shape: Size of each dimension (e.g., (3, 4) = 3 rows, 4 columns)
· For 2D arrays: axis=0 = rows (vertical), axis=1 = columns (horizontal)"""


# Understanding dimensions
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:")
print(f" {arr_1d} > shape: {arr_1d.shape}, ndim: {arr_1d.ndim} (axis 0 only)\n")

print("2D Array:")
print(f" {arr_2d}")
print(f" shape: {arr_2d.shape} (rows, columns)")
print(f" ndim: {arr_2d.ndim} (axis 0=rows, axis 1=columns)")

1D Array:
 [1 2 3 4 5] > shape: (5,), ndim: 1 (axis 0 only)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 shape: (3, 3) (rows, columns)
 ndim: 2 (axis 0=rows, axis 1=columns)


In [20]:
import numpy as np

# Axis in operations: specifies which dimension to collapse
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)

print(f"Shape: {matrix.shape}")

# axis=0: collapse rows (operate down columns)
# One value per column
sum_axis0 = np.sum(matrix, axis=0)

print(f"\naxis=0 (down rows): {sum_axis0}")
print(f"Shape: {sum_axis0.shape}")

print(
    f"Example: Column 0 sum = "
    f"{matrix[0,0]} + {matrix[1,0]} + {matrix[2,0]} = {sum_axis0[0]}"
)

print(
    f"Example: Column 1 sum = "
    f"{matrix[0,1]} + {matrix[1,1]} + {matrix[2,1]} = {sum_axis0[1]}"
)

# axis=1: collapse columns (operate across rows)
# One value per row
sum_axis1 = np.sum(matrix, axis=1)

print(f"\naxis=1 (across columns): {sum_axis1}")
print(f"Shape: {sum_axis1.shape}")

print(
    f"Example: Row 0 sum = "
    f"{matrix[0,0]} + {matrix[0,1]} + {matrix[0,2]} = {sum_axis1[0]}"
)

print(
    f"Example: Row 1 sum = "
    f"{matrix[1,0]} + {matrix[1,1]} + {matrix[1,2]} = {sum_axis1[1]}"
)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

axis=0 (down rows): [12 15 18]
Shape: (3,)
Example: Column 0 sum = 1 + 4 + 7 = 12
Example: Column 1 sum = 2 + 5 + 8 = 15

axis=1 (across columns): [ 6 15 24]
Shape: (3,)
Example: Row 0 sum = 1 + 2 + 3 = 6
Example: Row 1 sum = 4 + 5 + 6 = 15


In [22]:
#Statistical operation using the numpy
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array:", arr)

# Basic statistics
print(f"\n --- Basic Statistics --- ")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")

# 2D array statistics (with axis parameter)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n --- 2D Array Statistics --- ")
print("Matrix:")
print(matrix)
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum along rows (axis=0): {np.sum(matrix, axis=0)}") # Column sums
print(f"Sum along columns (axis=1): {np.sum(matrix, axis=1)}") #rows sums
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")
print(np.sum(matrix))

Array: [ 1  2  3  4  5  6  7  8  9 10]

 --- Basic Statistics --- 
Sum: 55
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Index of min: 0
Index of max: 9

 --- 2D Array Statistics --- 
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum along rows (axis=0): [12 15 18]
Sum along columns (axis=1): [ 6 15 24]
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
45


In [28]:
#Linear algebra
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)

# Element-wise multiplication (NOT matrix multiplication
print("\nElement-wise multiplication (a * b):")
print(a * b)

# Dot product of vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4,5,6])
print(f"\nDot product of vectors {v1} and {v2}: {np.dot(v1, v2)}")

# Matrix properties
matrix = np.array([[1, 2], [3, 4]])
print("\n --- Matrix Properties --- ")
print("Matrix:")
print(f"Determinant: {np.linalg.det(matrix)}")
print(f"Inverse:")
print(np.linalg.inv(matrix))
print(f"Transpose:")
print(matrix.T)

# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix)
print(f"\nEigenvalues: {eigenvals}")
print(f"Eigenvectors: n{eigenvecs}")

Matrix a:
[[1 2]
 [3 4]]

Matrix b:
[[5 6]
 [7 8]]

Element-wise multiplication (a * b):
[[ 5 12]
 [21 32]]

Dot product of vectors [1 2 3] and [4 5 6]: 32

 --- Matrix Properties --- 
Matrix:
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Transpose:
[[1 3]
 [2 4]]

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: n[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [30]:
#useful arrray method

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print("Original array:", arr)

# Sorting
print("\n --- Sorting --- ")
print("Sorted array:", np.sort(arr))
print("Original unchanged:", arr)
arr.sort() # In-place sort
print("After in-place sort:", arr)

# Unique elements
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
print("\n --- Unique Elements --- ")
print("Array:", arr_with_duplicates)
print("Unique values:", np.unique(arr_with_duplicates))

# Searching
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n --- Searching --- ")
print("Array:", arr)
print("Where is value > 5?", np.where(arr > 5))
print("Values where condition is True:", arr[np.where(arr > 5)])

# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4,5,6])

Original array: [3 1 4 1 5 9 2 6]

 --- Sorting --- 
Sorted array: [1 1 2 3 4 5 6 9]
Original unchanged: [3 1 4 1 5 9 2 6]
After in-place sort: [1 1 2 3 4 5 6 9]

 --- Unique Elements --- 
Array: [1 2 2 3 3 3 4]
Unique values: [1 2 3 4]

 --- Searching --- 
Array: [ 1  2  3  4  5  6  7  8  9 10]
Where is value > 5? (array([5, 6, 7, 8, 9]),)
Values where condition is True: [ 6  7  8  9 10]


In [39]:
#pratical example

# Simulate a grayscale image (2D array) with values 0-255
# Let's create a simple 10x10 "image"
image = np.random.randint(0, 256, size=(10, 10))
print("Original 'image' (10x10 array):")
print(image)

# Image operations
print(f"\n--- Image Statistics ---")
print(f"Brightness (mean): {np.mean(image):.2f}")
print(f"Contrast (std): {np.std(image):.2f}")
print(f"Min pixel value: {np.min(image)}")
print(f"Max pixel value: {np.max(image)}")
print(np.argmax(image))
print(np.std(image))
print(np.var(image))

# Brightness adjustment (add constant)
brighter = np.clip(image + 50, 0, 255) # Clip to valid range
print(f"\nBrightness increased (mean: {np.mean(brighter) :.2f})")

# Contrast adjustment (multiply)
contrast = np.clip(image * 1.5, 0, 255)
print(f"Contrast increased (std: {np.std(contrast) :.2f})")

Original 'image' (10x10 array):
[[ 58 133  65 181 196 181   8 126  27 252]
 [ 62 188 152   3   4 241 200  41  44 110]
 [ 27  94 160  94 222 217  38  85  55 154]
 [101  54 241 146  44 155  38 207  10  99]
 [126 204 119 225  68  37  34  17 214  50]
 [104 223 102   6  70 244 138  88 157  73]
 [115 251 193  87  75 221 137 171 143 193]
 [221  72 114 224 103 186 244  14 123  45]
 [144 180  78 187  19 136 215 165  61 194]
 [206 112  15   5 163 187 100   9 143  51]]

--- Image Statistics ---
Brightness (mean): 121.14
Contrast (std): 73.14
Min pixel value: 3
Max pixel value: 252
9
73.13850148861404
5349.240399999999

Brightness increased (mean: 167.31)
Contrast increased (std: 86.54)


In [ ]:
## 15. Common NumPy Functions Cheat Sheet

"""Quick reference for frequently used NumPy functions."""

# Array Creation
# np.array(), np.arange(), np.linspace(), np.zeros(), np.ones()
# np.full(), np.eye(), np.random.rand(), np.random.randint()

# Array Information
# .shape, .size, .ndim, .dtype, .itemsize, .nbytes

# Array Manipulation
# .reshape(), .flatten(), .T (transpose)
# np.concatenate(), np.vstack(), np.hstack()
# np.split(), np.array_split()

# Mathematical Operations
# +, -,*, /, ** ,%, np.sqrt(), np.sin(), np.cos(), np.exp(), np.log()

# Statistical Functions
# np.sum(), np.mean(), np.median(), np.std(), np.var()
# np.min(), np.max(),np.argmin(),np.argmax()
# np.percentile(), np.quantile()

# Linear Algebra
# np.dot(),@ (matrix multiplication)
# np.linalg.det(), np.linalg.inv(), np.linalg.eig()
# np.linalg.solve() (solve linear equations)

# Searching and Sorting
# np.where(), np.argwhere()
# np.sort(), .sort() (in-place)
# np.unique(), np.searchsorted()

# Array Comparison
# == , != , <, >, <= , >=
# np.all(), np.any(), np.isnan(),np.isinf()